
# SEO settings
title: "Robo"
title2: "bits" # default: ""
description: "Personal blog covering adventures in robotics development and more"
keywords: "SEO, blog, web, thinkspace, robotics, engineering, student, DIY, electronics, engineering, space"
url: http://ausshir.github.io # site url
# baseurl: "" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-84599606-1
repo: http://github.com/ausshir/ausshir.github.io
disqus_shortname: "ausshir"
twitter_username: "austinshirley"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Austin Shirley"
  job      : "senior CME student at USask"
  bio      : "Working on robotics and space projects for the USST and a little in my free time too!"
  thumb    : /images/author.jpg
  email    : ausshir@gmail.com
  url      : http://ausshir.github.io
  github   : http://github.com/ausshir
  twitter  : http://twitter.com/austinshirley
  facebook : https://www.facebook.com/AustinShirley
  linkedin : https://ca.linkedin.com/in/ausshir

# social settings
og_locale: "en_CA"
twitter_card: "summary_large_image"
twitter_site: "@austinshirley"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
